server {
    listen 8000;
    server_name localhost;
    server_tokens off;

    access_log /dev/stdout;
    error_log /dev/stderr debug;

    location /assets/ {
        alias /app/public/assets/;
        access_log off;
        expires 30d;
    }

    location / {
        root /app/web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}