server {
    listen 8000;
    server_name localhost;
    server_tokens off; # Oculta a versão do Nginx por segurança

    # 1. Rotas Estáticas de Assets (Imagens, Favicon, etc.)
    location /assets/ {
        alias /app/public/assets/;
        access_log off;
        expires 30d;
    }

    # 2. Rotas de Interface Web (HTML)
    location / {
        root /app/web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 3. Rota Blindada da API (Envia para o Python local)
    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}